version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: api-lumen-mysql
    volumes:
      - "./docker/mysql/data/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: api-lumen
    restart: always
    networks:
      - private-network
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    image: api-lumen/php
    restart: always
    container_name: api-lumen-php
    volumes:
      - ./api:/var/www/html
      - /var/www/vendor
    ports:
      - "8000:8000"
    networks:
      - private-network
    depends_on:
      - mysql
networks:
  private-network:
    name: private-network
    driver: bridge